# Generated by Django 2.1.2 on 2018-10-23 17:16

import dj_literature.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(max_length=200, unique=True)),
                ('dateadded', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('datemodified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('parentcollection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.PositiveSmallIntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('dateadded', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('datemodified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatortype', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedeleted', models.DateTimeField(auto_now_add=True, verbose_name='deleted date')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileTypeMimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimetype', models.CharField(max_length=200, unique=True)),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.FileType')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateadded', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('datemodified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=dj_literature.models.itemattachment_filename)),
                ('mimetype', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item')),
                ('sourceitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dj_literature.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.PositiveSmallIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Creator')),
                ('creatortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.CreatorType')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Field')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(verbose_name='Content')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item')),
                ('sourceitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dj_literature.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=200, unique=True)),
                ('display', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeCreatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryfield', models.PositiveSmallIntegerField()),
                ('creatortype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.CreatorType')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.ItemType')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.PositiveSmallIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Field')),
                ('itemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.ItemType')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tagtype', models.PositiveSmallIntegerField(default=1)),
                ('dateadded', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('datemodified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.AddField(
            model_name='itemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.ItemType'),
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_literature.Item'),
        ),
    ]
